### ISSUE TITLE
[BUG]: Crash when make a world caused by an incompat with awakeningmeat

### ISSUE THREAD

**Issue by quentin452** [Thorfusion/Mekanism-Community-Edition#116]
### Describe the bug

The world cannot be load if i use awakening meats to mekanism

### To Reproduce

1. launch a world
2. crash

### Expected behavior

Crash when make a world

### Mekanism Version

Mekanism-Community-Edition-1.7.10-9.10.28-Core

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Linux

### The crash report in folder ./crash-reports (both server and client logs)

```shell
[latest.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11405748/latest.log)

Don't have crash report
```

**Comment by DrParadox7** [comment]
This doesn't seem to be a Mekanism issue. The value `wild` is returning null when Mekanism has already a null check:
https://github.com/Thorfusion/Mekanism-Community-Edition/blob/31885645f0c4a553147021ef620bbd922460920c/src/main/java/mekanism/api/util/StackUtils.java#L58
It must be investigated and fixed in AwakeningMeat side.
