### ISSUE TITLE
[BUG]: Auto-Sort not working

### ISSUE THREAD

**Issue by 4dam3k** [Thorfusion/Mekanism-Community-Edition#146]
### Describe the bug

The bug is exactly as written in title and "To reproduce"

### To Reproduce

1. Place factory
2. Turn Auto-Sort ON
3. Put items
4. Not sorting

### Expected behavior

Auto sorting doing it's thing

### Mekanism Version

9.12.7

### Minecraft Version is this regarding?

1.12.2

### What OS are you seeing the problem on?

Windows

### Name of modpack if applicable

Enigmatica 2 Expert: Unofficial

### Version of said modpack if applicable

1.3.8.1

### Screenshots

![image](https://github.com/Thorfusion/Mekanism-Community-Edition/assets/66412368/2e99a5ed-b45f-413f-8190-4dae5ea28c63)

### The crash report in folder ./crash-reports (both server and client logs)

```shell
It's not a crash
```

### Please provide the following other files

[latest.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/12921282/latest.log)
m
[mekanism.zip](https://github.com/Thorfusion/Mekanism-Community-Edition/files/12921292/mekanism.zip)

**Comment by maggi373** [comment]
well, it auto sorts when i tried to replicate, but i did manage to dupe with it. need more testing for that.

**Comment by sddsd2332** [comment]
This is a low probability of a problem and cannot be reproduced under normal circumstances.
I kept the old state sort [here](https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2/blob/RFG/src/main/java/mekanism/common/tile/TileEntityFactory.java#L301C1-L303) to fix this problem, click switch to the old sort when the machine is running, it works normally, but at this time switching to the new sequencing, it may cause the factory to not be able to continue sorting, I think it may be caused by the slot problem when the machine is working when switching from the old state of the sort to the new state of sorting

**Comment by 4dam3k** [comment]
@sddsd2332 
How can I enable this old sorting?

**Comment by maggi373** [comment]
if others have issue with this please upvote

checking if this is a one time off or not

**Comment by Azami1990** [comment]
Replaced Mek in E2EE Skyblock. 
Cant get it to sort. im on 9.12.8 1.12

**Comment by maggi373** [comment]
#176 adds config option to disable the new sorting algorithm
