### ISSUE TITLE
[BUG] Don't even starting

### ISSUE THREAD

**Issue by Gargule** [Thorfusion/Mekanism-Community-Edition#27]
Sorry for deleting template.
When i trying to start Minecraft with your last release i have this:
`CB's DepLoader was unable to download required library CodeChickenLib-1.7.10-1.1.3.141-universal.jar Check your internet connection and try restarting or download it manually from https://files.thorfusion.com/mekanism/CodeChickenLib-1.7.10-1.1.3.141-universal.jar and put it in your mods folder`
(Yes, i'm using custom launcher)
Also i have CodeChickenLib-1.7.10-1.1.3.138-universal in my "mods" and it's ignored.

**Comment by maggi373** [comment]
Open the link in your browser and see if its working.
If you cant download the file from the browser send me error shown
If its works please send me the crash log that forge makes

**Comment by maggi373** [comment]
I have probably figured out the issue, due to the high bot attacks from both china and russia and few others, those countries were blocked in 2020, and it seems that you reside in one of them. Forgot that mekanism still uses our hosting. Would love to host the files on github but its against their tos. 

You can download the file from: https://technic-solder.eu-central-1.linodeobjects.com/maven/CodeChickenLib-1.7.10-1.1.3.141-universal.jar and put the file in your mods folder.

I also need to note that your modpack/launcher DOES NOT CONFORM to standard practices. If youre creating a modpack and making it available to others you need to include all files, including what deploader downloads. deploader is there for people that does not know how dependencies works and put alot of traffic on the server. Think what would happen if everyone didnt include the files. You also does not include credits for those mods being downloaded wich is also against their licenses.

**Comment by Gargule** [comment]
Yes, im from one of those countries. Thank you for link. 
And thing about my modpack:
1. It's very-very "in dev"
2. It's for me and 5-7 my friends.
3. Credits will be as soon as i'll done with modlist.

To be honest, now my modpack is against some other terms from licenses of it's mods.
