### ISSUE TITLE
[BUG]: Hodgepodge speedupVanillaFurnace disables Energized Smelter

### ISSUE THREAD

**Issue by AstroTibs** [Thorfusion/Mekanism-Community-Edition#86]
### Describe the bug

When using Mekanism CE (any release, or even the final non-CE release) alongside Hodgepodge (any release), using the Hodgepodge option **speedupVanillaFurnace** set to `true` prevents the Energized Smelter from smelting anything. Presumably, it doesn't recognize any furnace recipes.

I've reported this to Hodgepodge. The devs think it's an issue on Mekanism's end.

https://github.com/GTNewHorizons/Hodgepodge/issues/165

### To Reproduce

Use Mekanism with Hodgepodge.
Set **speedupVanillaFurnace** to `true`.
Try to use Energized Smelter to smelt anything.

### Expected behavior

The E.S. should smelt.
Clearly it hooks off of the furnace recipes somehow, but the Hodgepodge devs think E.S. recipe checking is "overly strict."

### Mekanism Version

9.10.23-Core

### Minecraft Version is this regarding?

1.7.10

### The crash report in folder ./crash-reports (both server and client logs)

```shell
https://mclo.gs/xZ1LcoP (PolyMC log)

https://github.com/GTNewHorizons/Hodgepodge/files/10476991/fml-client-latest.log (latest log upload)
```

**Comment by maggi373** [comment]
is the desired result to speed up the energized smelter or not?

**Comment by AstroTibs** [comment]
That is not the desired result.
That option is to speed up "recipe lookup."

`# Speedup Vanilla Furnace recipe lookup`
`B:speedupVanillaFurnace=false`

**Comment by mitchej123** [comment]
The vanilla furnace, by default, iterates over the entire list for every lookup, resulting in lag in large packs.  We sped that up by using a specialized item stack map.  Since mekanism is copying it to their own recipe map the fix won't apply.   We resolved the nbt returns when iterating over an nbt insensitive map which was causing issues.

**Comment by maggi373** [comment]
closing this issue because gtnh mainly fixed on their side, while this is a bug that needs to fixed at some point, as per mentioned issue, you cant smelt dna sample's, changing might require alot of rework. we neither have time nor is hodgepodge an supported mod (might change in the future). the official modpacks have other mods that can do this job when mek cant smelt stuff with nbt tags.
